# Linear Algebra for CpE
## Laboratory 7 : Matrix Operations

Coded and submitted by: <br>
Panelo, Bryan V. <br>
58001

## Activity
##### Six Matrix Multiplication Properties
#COMMUTATIVE PROPERTY OF MULTIPLICATION DOES NOT HOLD <br>
1.) $AB \neq BA$ <br>
#ASSOCIATIVE PROPERTY OF MULTIPLICATION <br>
2.) $(AB)C = A(BC)$<br>
#DISTRIBUTIVE PROPERTY<br>
3.) $A(B + C) = AB + AC$<br>
&nbsp;&nbsp;&nbsp; $(B + C) A = BA + CA$<br>
#MULTIPLICATIVE IDENTITY OF PROPERTY<br>
4.) $IA = A and AI = A$ <br>
#MULTIPLICATIVE PROPERTY OF ZERO<br>
5.) $0A = 0 and A0= 0$<br>
#DIMENSION PROPERTY<br>
6.) $Product$ $of$ $an$  $m$ $x$ $n$  $matrix$  $and$ $an$ $n x k$ $is$ $an$ $m$ x $k$ $matrix$


### Task 1

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than $(3,3)$.
In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [40]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
C = np.array([
    [1,2,1],
    [2,3,2],
    [4,2,3]
])
I = np.eye(3)
zero = np.zeros((3,3))

X = np.array([
    [2,3,4,],
    [3,2,1,],
    [2,3,2,]
])
Y = np.array([
    [2,1,2,],
    [2,1,1,],
    [1,1,1,]
])

In [33]:
#1.)

A_B = A@B 
B_A = B@A
print("A_B is:\n", A_B)
print("B_A is:\n", B_A)

#to prove that they're not equal
pr = np.array_equal(A_B,B_A)
print("The two array are equal:", pr)    

A_B is:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
B_A is:
 [[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
The two array are equal: False


In [34]:
#2.) 
E1 = (A@B)@C
E2 = A@(B@C)
print("E1 is:\n", E1)
print("E2 is:\n", E2)

#to prove that the given equation is equal 
pr = np.array_equal(E1,E2)
print("The two array are equal:", pr)

E1 is:
 [[150 168 132]
 [438 483 384]
 [726 798 636]]
E2 is:
 [[150 168 132]
 [438 483 384]
 [726 798 636]]
The two array are equal: True


In [44]:
#3.)

E1  = A@(B+C)
E_1 = (A@B)+(A@C)
print("E1 is:\n", E1)
print("E_1 is:\n", E_1)
#to prove that the given equation is equal 
pr = np.array_equal(E1,E_1)
print("The two array are equal:", pr)
print("")
print("")
E2  = (B+C)@A
E_2 = (B@A)+(C@A)
print("E2 is:\n", E2)
print("E_2 is:\n", E_2)
pr2 = np.array_equal(E2,E_2)
print("The two array are equal:", pr2)

E1 is:
 [[ 47  38  32]
 [122 104  86]
 [197 170 140]]
E_1 is:
 [[ 47  38  32]
 [122 104  86]
 [197 170 140]]
The two array are equal: True


E2 is:
 [[106 134 162]
 [ 82 104 126]
 [ 51  66  81]]
E_2 is:
 [[106 134 162]
 [ 82 104 126]
 [ 51  66  81]]
The two array are equal: True


In [35]:
#4.)

I1 = I@A
I_1 = A
print("I1 is:\n", I1)
print("I_1 is:\n", I_1)
pr = np.array_equal(I1,I_1)
print("The two array are equal:", pr)
print("")
print("")

I2 = A@I
I_2 = A
print("I2 is:\n", I2)
print("I_2 is:\n", I_2)
pr = np.array_equal(I2,I_2)
print("The two array are equal:", pr)

I1 is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
I_1 is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The two array are equal: True


I2 is:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
I_2 is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
The two array are equal: True


In [36]:
#5.) 

Z1 = zero@A
Z_1 = 0
print("Z1 is:\n", Z1)
print("Z1 is:\n", Z_1)
pr = np.array_equal(Z1,Z_1)
print("")
print("")

Z2 = A@zero
Z_2 = 0
print("Z1 is:\n", Z2)
print("Z1 is:\n", Z_2)
pr = np.array_equal(Z2,Z_2)

Z1 is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Z1 is:
 0


Z1 is:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Z1 is:
 0


In [58]:
#6.)

E1 = (X@Y)@(Y@A) 
E2 = (X@A)
print("E1 is:\n", E1)
print("E2 is:\n", E2)
print("E3 is:\n", E3)
E3 = E1@E2
print(E3)
print(E1.shape)
print(E2.shape)
print(E3.shape)
pro = np.array_equal(E1@E2,E3)
print(pro)

E1 is:
 [[529 668 807]
 [406 512 618]
 [439 554 669]]
E2 is:
 [[42 51 60]
 [18 24 30]
 [28 35 42]]
E3 is:
 [[56838 71256 85674]
 [43572 54624 65676]
 [47142 59100 71058]]
[[56838 71256 85674]
 [43572 54624 65676]
 [47142 59100 71058]]
(3, 3)
(3, 3)
(3, 3)
True
